const posts = [
  {
    "id": "post_001",
    "title": "The Mediterranean Monk Seal: A Species at the Edge",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Monachus_monachus.jpg/1200px-Monachus_monachus.jpg",
    "excerpt": "With fewer than 800 individuals remaining in the wild, the Mediterranean Monk Seal is one of the most endangered marine mammals on Earth. Here is what the numbers do not tell you.",
    "date": "May 2026",
    "content": "<p>There is a particular kind of silence that comes with critically endangered species. Not the silence of absence — not yet — but the silence of a population so reduced that encounters become remarkable rather than ordinary.</p><p>The Mediterranean Monk Seal (<em>Monachus monachus</em>) lives in that silence. Fewer than 800 individuals remain distributed across fragmented coastlines in Greece, Turkey, and the Atlantic coast of Mauritania. They prefer sea caves, isolated beaches, and underwater grottos — places that kept them safe from human pressure for centuries, but now isolate small subpopulations from each other.</p><h2>Why This Species Matters</h2><p>Monk seals are what ecologists call an <strong>indicator species</strong> — their health reflects the condition of the broader Mediterranean marine ecosystem. A coastline that cannot support monk seals is a coastline under serious ecological stress.</p><p>They are also relict fauna — survivors of a lineage that stretches back millions of years. Losing this species is not only a conservation failure. It is the permanent erasure of an evolutionary line.</p><blockquote>&quot;We are not losing animals. We are losing entire evolutionary experiments.&quot;</blockquote><p>Current population surveys suggest the species has shown marginal recovery in Greece, largely due to protected marine areas. But the margins remain dangerously thin. A single disease event, an oil spill, or an extended period of low fish availability could collapse a subpopulation entirely.</p><p>I will continue documenting what we know — and what we are at risk of never knowing — in future notes.</p>"
  },
  {
    "id": "post_002",
    "title": "What Does It Mean to Study a Species With 800 Left",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Mediterranean_monk_seal_-_Monachus_monachus.jpg/1200px-Mediterranean_monk_seal_-_Monachus_monachus.jpg",
    "excerpt": "Working with critically endangered species changes how you think about observation, documentation, and time. Some field notes on what the numbers feel like when you are close to them.",
    "date": "April 2026",
    "content": "<p>When you work in conservation research, even at the level I do — assisting, reviewing literature, processing data — you become fluent in a particular kind of arithmetic. Population counts. Habitat loss percentages. Generation lengths. Extinction probabilities.</p><p>Most of the time, these numbers remain abstract. They are entries in a database, citations in a paper.</p><p>But occasionally a number becomes real.</p><h2>The Weight of 800</h2><p>Eight hundred is not a large number. It is a mid-sized lecture hall. It is a village. It is the number of people who might ride a single metro train in the morning.</p><p>For the Mediterranean Monk Seal, it is an entire species.</p><p>Working with population data for a species at this threshold changes how you read the numbers. Every confirmed individual matters differently than it would in a species with healthy population buffers. Every unconfirmed sighting carries weight. Every reported death is recorded with a kind of reluctant gravity.</p><p>Dr. Chen, whose work I assist, describes it as <em>&quot;research with stakes you cannot fully detach from.&quot;</em> I think that is accurate.</p><h2>Why Documentation Matters Now</h2><p>There is an argument in conservation biology that the most important work we can do for the most endangered species is simply to <strong>document thoroughly</strong> — to build the most complete scientific record possible while we still can. Not just for conservation planning, but as a form of record-keeping for what existed.</p><p>That instinct is part of what drives these field notes. A species this rare deserves careful witness.</p>"
  }
];
